version: "3.9"
services:

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    networks:
      - dir-service-net
      
  solr:
    image: "solr:8.6.3"
    networks:
      - dir-service-net
    ports:
      - "8983:8983"
    volumes:
      - ./solrdata:/var/solr  
  
  userservice:
    depends_on:
      - redis
    environment:
      - spring.redis.host=redis
    image: "bc92/user-service:latest"
    ports:
      - "2081:2081"
    networks:
      - dir-service-net
      
  dirservice:
    depends_on:
      - redis
      - solr
    environment:
      - spring.redis.host=redis
      - solr.host=http://solr:8983/solr
    image: "bc92/directory-service:latest"
    ports:
      - "2090:2090"
    networks:
      - dir-service-net

networks:
  dir-service-net:
    driver: bridge

