version: "3.9"
services:

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    networks:
      - dir-service-net
      
  solr:
    image: "solr:8.6.3"
    networks:
      - dir-service-net
    ports:
      - "8983:8983"
    volumes:
      - ./solrdata:/var/solr  
  
  userservice:
    depends_on:
      - redis
    environment:
      - spring.redis.host=redis
    image: "bc92/user-service"
    ports:
      - "2081:2081"
    networks:
      - dir-service-net

networks:
  dir-service-net:
    driver: bridge

